# Generated by Django 4.0.1 on 2022-01-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
